-- ============================================================
-- mambo - Pipeline - recarga COMPLETA con pipedrive_id (132 negocios)
-- Fuente: "Tercera base de datos app pipeline.csv"
-- Pega TODO esto en: Supabase -> SQL Editor -> New query -> Run
-- Requiere que la tabla "deals" y la columna pipedrive_id existan
-- (correr antes schema.sql y migration-001-pipedrive-id.sql).
--
-- Vacia los datos actuales (de prueba) SIN borrar la estructura ni columnas.
-- ============================================================

truncate table public.deals restart identity;

insert into public.deals
  (pipedrive_id, org, title, owner, stage, amount, prob, comment, status, loss_reason, vertical, client_type, industry, source, close_date)
values
  (3189, 'Tándem', 'Tándem Asesorías estratégicas cultura', 'Mauricio', 'propuesta', 3500, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', '', 'Clientes actuales (Profundización)', '2026-08-31'),
  (3188, 'Banco Santander', 'Banco Santander - gestión del cambio', 'Nicolás Aramburú', 'primera', 80000, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Senseis', NULL),
  (3186, 'Equans', 'Equans - Coaching individual al liderazgo', 'Mauricio', 'cierre', 3500, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', 'Energía', 'Clientes actuales (Profundización)', '2026-08-31'),
  (3185, 'Equans', 'Equans - Cadena de valor de talento (reclutamiento y onboarding)', 'Mauricio', 'primera', 20000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', 'Energía', 'Clientes actuales (Profundización)', '2026-09-30'),
  (3184, 'La Calera', 'La Calera - Talleres cultura y clima', 'Cristina Mc', 'propuesta', 3000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente antiguo', 'Agroindustrial', 'Contactos personales (Partners)', '2026-07-01'),
  (3183, 'Terminales Portuarios Euroandinos', 'Terminales Portuarios Euroandinos - Planeamiento cultural', 'Guillermo Solano', 'cierre', 55250, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Logística', 'Contactos personales (Partners)', '2026-07-28'),
  (3180, 'OSTERLING ABOGADOS', 'OSTERLING ABOGADOS', 'Renzo Duarte', 'contacto', 0, 25, '', 'activo', '', '', 'Cliente nuevo', 'Servicios', 'Mamberos', NULL),
  (3179, 'PC MODA SAC', 'PC MODA SAC', 'Renzo Duarte', 'contacto', 0, 25, '', 'activo', '', '', 'Cliente nuevo', 'Textil', 'Mamberos', '2026-07-31'),
  (3175, 'UNACEM', 'UNACEM - plan de tecnología para gestión humana', 'Nicolás Aramburú', 'cierre', 18000, 75, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Industrial', 'Contactos personales (Partners)', '2026-06-30'),
  (3174, 'Montana', 'Montana - Planeamiento + Transformación Digital', 'Renzo Duarte', 'propuesta', 25000, 75, '', 'activo', '', 'Marca & Experiencia', 'Cliente actual', 'Industrial', 'Contactos personales (Partners)', '2026-06-30'),
  (3173, 'Montana', 'Montana - AI', 'Renzo Duarte', 'primera', 15000, 50, '', 'activo', '', 'Transformación Digital', 'Cliente actual', 'Industrial', 'Contactos personales (Partners)', '2026-08-30'),
  (3171, 'FAO', 'FAO', 'Renzo Duarte', 'contacto', 0, 25, '', 'activo', '', 'Transformación Digital', 'Cliente nuevo', 'Agroindustrial', 'Mamberos', NULL),
  (3169, 'Credicorp Capital', 'Credicorp Capital - transformación cultural', 'Nicolás Aramburú', 'cierre', 71000, 75, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Banca', 'Contactos personales (Partners)', '2026-06-30'),
  (3168, 'Abbott', 'Abbott - transformación cultural', 'Nicolás Aramburú', 'cierre', 18000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Salud', 'Senseis', '2026-06-30'),
  (3166, 'Bituper', 'Bituper - Estrategia Comercial', 'Guillermo Solano', 'cierre', 17000, 50, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Infraestructura, servicios y construcción', 'Contactos personales (Partners)', '2026-07-01'),
  (3165, 'Falabella', 'Falabella - modelo de liderazgo', 'Nicolás Aramburú', 'cierre', 36000, 75, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Retail', 'Contactos personales (Partners)', '2026-06-30'),
  (3162, 'Interbank', 'Interbank - Gestión del Cambio', 'Nicolás Aramburú', 'cierre', 100000, 75, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Banca', 'Canales Mamberos', '2026-07-01'),
  (3161, 'Indeco - Lanzark', 'Indeco', 'Renzo Duarte', 'primera', 15000, 50, '', 'activo', '', 'Transformación Digital', 'Cliente nuevo', 'Industrial', 'Canales Mamberos', '2026-06-30'),
  (3159, 'Equans', 'Equans - Programa de Mentoring', 'Nicolás Aramburú', 'cierre', 13500, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', 'Servicios', 'Contactos personales (Partners)', '2026-06-30'),
  (3157, 'JyS Asesoria Empresarial', 'JyS Asesoria Empresarial - Planeamiento Estrategico', 'Cristina Mc', 'cierre', 24000, 50, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Servicios', 'Canales Mamberos', '2026-07-01'),
  (3156, 'JyS Asesoria Empresarial', 'JyS Asesoria Empresarial - Branding', 'Cristina Mc', 'cierre', 8000, 25, '', 'activo', '', 'Marca & Experiencia', 'Cliente nuevo', 'Servicios', 'Canales Mamberos', '2026-07-01'),
  (3151, 'Bancomercio', 'Bancomercio', 'Renzo Duarte', 'cierre', 20000, 75, '', 'activo', '', 'Transformación Digital', 'Cliente antiguo', 'Banca', 'Mamberos', '2026-06-30'),
  (3148, 'UNACEM', 'UNACEM- Comunicacion Interna', 'Cristina Mc', 'nurturing', 25000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', 'Industrial', 'Canales Mamberos', '2026-07-01'),
  (3143, 'Gallagher', 'Gallagher', 'Renzo Duarte', 'contacto', 0, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Servicios', 'Mamberos', NULL),
  (3141, 'Fibra Prime', 'Fibra Prime - Digitalización', 'Cristina Mc', 'contacto', 0, NULL, '', 'activo', '', 'Transformación Digital', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (3140, 'Olympic', 'Olympic - Estrategia de reposicionamiento Gas', 'Cristina Mc', 'cierre', 35000, 50, '', 'activo', '', 'Marca & Experiencia', 'Cliente nuevo', 'Petróleo y gas', 'Contactos personales (Partners)', '2026-07-01'),
  (3139, 'Ecopacking', 'Ecopacking - Campaña de posicionamiento', 'Nicolás Aramburú', 'cierre', 10000, 50, '', 'activo', '', 'Marca & Experiencia', 'Cliente actual', 'Industrial', 'Contactos personales (Partners)', '2026-07-08'),
  (3138, 'Yichang', 'Yichang - AI discovery', 'Nicolás Aramburú', 'contacto', 20000, NULL, '', 'activo', '', 'Transformación Digital', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (3137, 'Agrícola Don Ricardo', 'Agrícola Don Ricardo - Planeamiento estratégico', 'Nicolás Aramburú', 'cierre', 42000, 25, '', 'activo', '', 'Estrategia', 'Cliente actual', 'Agroindustrial', 'Contactos personales (Partners)', '2026-09-01'),
  (3134, 'La Dominga', 'La Dominga - Propuesta de valor y experiencia del cliente', 'Cristina Mc', 'contacto', 0, NULL, '', 'activo', '', 'Marca & Experiencia', '', '', 'Contactos personales (Partners)', NULL),
  (3131, 'REF', 'REF - Coaching líderes (Chene)', 'Mauricio', 'cierre', 3500, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Servicios', 'Clientes actuales (Profundización)', '2026-08-06'),
  (3130, 'Inkas Berries', 'Inkas Berries - por verse', 'Nicolás Aramburú', 'target', 0, NULL, '', 'activo', '', '', '', '', '', NULL),
  (3126, 'Belmond', 'Belmond - EVP', 'Mauricio', 'cierre', 20000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Hotelería y Turismo', 'Senseis', '2026-06-30'),
  (3124, 'Grupo Kaufmann', 'Grupo Kaufmann', 'Renzo Duarte', 'target', 20000, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', '', 'Automotriz', 'Contactos personales (Partners)', '2026-06-30'),
  (3123, 'Grupo Andino', 'Grupo Andino - planeamiento estratégico cultural', 'Renzo Duarte', 'primera', 20000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Transporte', 'Contactos personales (Partners)', '2026-08-30'),
  (3122, 'Cementos Pacasmayo', 'Cementos Pacasmayo', 'Renzo Duarte', 'primera', 20000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Infraestructura, servicios y construcción', 'Contactos personales (Partners)', '2026-06-30'),
  (3117, 'Renzo Costa', 'Renzo Costa - Programa de liderazgo', 'Mauricio', 'target', 10000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-06-30'),
  (3116, 'CSTI Corp', 'CSTI Corp - Capacitacion IA', 'Cristina Mc', 'target', 0, NULL, '', 'activo', '', '', '', '', 'Contactos personales (Partners)', NULL),
  (3112, 'Fonafe', 'Fonafe', 'Guillermo Solano', 'cierre', 45000, 50, '', 'activo', '', 'Estrategia', 'Cliente antiguo', 'Servicios públicos', 'Canales Mamberos', '2026-07-01'),
  (3111, 'Pisco Lablanco', 'Energy Drinks - Investigación de Mercado', 'Guillermo Solano', 'cierre', 38000, 50, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Bebidas', 'Mamberos', '2026-07-01'),
  (3107, 'Farmacia Universal', 'Farmacia Universal - Proyecto 2', 'Mauricio', 'contacto', 15000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', 'Servicios', 'Clientes actuales (Profundización)', '2026-07-31'),
  (3106, 'Farmacia Universal', 'Farmacia Universal - Planeamiento estratégico', 'Guillermo Solano', 'contacto', 20000, 50, '', 'activo', '', 'Estrategia', 'Cliente actual', 'Servicios', 'Clientes actuales (Profundización)', '2026-07-01'),
  (3105, 'VyV Inmobiliaria', 'VyV Inmobiliaria - Capacitación liderazgo y cultura', 'Nicolás Aramburú', 'cierre', 10000, 75, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Infraestructura, servicios y construcción', 'Contactos personales (Partners)', '2026-07-01'),
  (3104, 'Pacific Control (Laboratorios Scerpella)', 'Pacific Control - Cultura', 'Mauricio', 'target', 40125, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Servicios', 'Mamberos', '2026-07-31'),
  (3102, 'San Fernando', 'San Fernando - Procesos', 'Mauricio', 'primera', 15000, 50, '', 'activo', '', 'Estrategia', 'Cliente antiguo', 'Agroindustrial', 'Clientes antiguos (Recuperación)', '2026-06-30'),
  (3098, 'Aceros Arequipa', 'Aceros Arequipa - Planeamiento Cultural', 'Mauricio', 'target', 40000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Industrial', 'Contactos personales (Partners)', '2026-06-30'),
  (3096, 'Celaris', 'Celaris - Gestión de RS', 'Topless', 'target', 0, 25, '', 'activo', '', '', 'Cliente nuevo', '', 'Senseis', NULL),
  (3093, 'Montana', 'Implementación TI Proyectos', 'Renzo Duarte', 'primera', 50000, 50, '', 'activo', '', 'Transformación Digital', '', 'Industrial', 'Contactos personales (Partners)', '2026-04-30'),
  (3087, 'Redondos', 'Redondos - Cultura de Felicidad', 'Mauricio', 'target', 10000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Senseis', '2026-05-31'),
  (3085, 'VyV Inmobiliaria', 'VyV Inmobiliaria - Cultura y liderazgo', 'Nicolás Aramburú', 'cierre', 40000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Infraestructura, servicios y construcción', 'Contactos personales (Partners)', '2026-07-31'),
  (3083, 'Alliance Risk & Protection', 'Alliance Risk & Protection - Diagnostico Cultural', 'Topless', 'target', 0, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', '', '', 'Contactos personales (Partners)', NULL),
  (3081, 'Ficohsa', 'Ficohsa', 'Mauricio', 'cierre', 61000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Banca', 'Canales Mamberos', '2026-07-01'),
  (3078, 'Banbif', 'Banbif - EVP y marca empleadora', 'Mauricio', 'cierre', 30000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Banca', 'Mamberos', '2026-06-30'),
  (3077, 'Inka Tubos', 'Inka Tubos', 'Guillermo Solano', 'target', 30000, 25, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Senseis', NULL),
  (3074, 'Peru Fashions', 'Peru Fashions', 'Renzo Duarte', 'target', 20000, 25, '', 'activo', '', 'Estrategia', '', 'Textil', 'Contactos personales (Partners)', '2026-05-31'),
  (3073, 'Blu', 'Blu', 'Renzo Duarte', 'primera', 40000, 50, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Servicios', 'Contactos personales (Partners)', '2026-05-31'),
  (3068, 'Terpel', 'Terpel - Capacitaciones mandos medios y analistas (Belen)', 'Mauricio', 'target', 20000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Mamberos', '2026-06-11'),
  (3067, 'Terpel', 'Terpel - Planeamiento cultural', 'Mauricio', 'target', 42500, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Mamberos', '2026-06-11'),
  (3061, 'MEF', 'MEF - Planeamiento cultural', 'Mauricio', 'target', 53500, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Servicios', 'Canales Mamberos', '2026-08-03'),
  (3059, 'UNACEM', 'UNACEM', 'Guillermo Solano', 'nurturing', 72000, NULL, '', 'activo', '', 'Estrategia', 'Cliente actual', 'Industrial', 'Clientes actuales (Profundización)', NULL),
  (3057, 'Montana', 'Sostenibilidad', 'Renzo Duarte', 'target', 20000, 50, '', 'activo', '', 'Ventas', 'Cliente antiguo', 'Industrial', 'Mamberos', '2026-03-28'),
  (3055, 'MEF', 'MEF - índice y esencia cultural', 'Mauricio', 'target', 11000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Servicios', 'Canales Mamberos', '2026-08-13'),
  (3048, 'Tailoy', 'Tailoy', 'Renzo Duarte', 'primera', 30000, 25, '', 'activo', '', 'Ventas', 'Cliente nuevo', 'Retail', 'Contactos personales (Partners)', '2026-03-28'),
  (3034, 'DC Capital', 'Grupo DC- Manual de Crisis Empresas', 'Cristina Mc', 'nurturing', 20000, 25, '', 'activo', '', '', '', '', 'Contactos personales (Partners)', NULL),
  (3025, 'Grupo Minero Sinchi Wayra', 'Grupo Minero Sinchi Wayra - transformación cultural desde el liderazgo', 'Nicolás Aramburú', 'cierre', 40000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Minería', 'Contactos personales (Partners)', '2026-07-06'),
  (3021, 'Terpel', 'Terpel- Marca Vehículo Cultural', 'Mauricio', 'target', 33000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', '', '', 'Canales Mamberos', '2026-06-11'),
  (3020, 'Oeschle', 'Oeschle - Planeamiento cultural', 'Mauricio', 'target', 30000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Retail', 'Canales Mamberos', '2026-06-30'),
  (3018, 'Catalogo SAC', 'Catalogo SAC', 'Renzo Duarte', 'target', 98000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Textil', 'Contactos personales (Partners)', '2026-03-19'),
  (3015, 'Caja Cusco', 'Caja Cusco', 'Mauricio', 'target', 30000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-02-27'),
  (3014, 'Zest Capital', 'Zest Capital', 'Mauricio', 'target', 10000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Canales Mamberos', '2026-02-28'),
  (3006, 'Illusione', 'Illusione - Automatización de procesos de clientes', 'Renzo Duarte', 'target', 30000, 75, '', 'activo', '', 'Transformación Digital', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-07-15'),
  (3005, 'Yape (iO)', 'Yape (iO)', 'Mauricio', 'target', 10000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-03-31'),
  (3000, 'BBB', 'BBB - transformación cultural y ventas', 'Nicolás Aramburú', 'target', 30000, 75, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Retail', 'Contactos personales (Partners)', '2026-02-23'),
  (2998, 'Banco Pichincha', 'Banco Pichincha - Operativización del nuevo modelo operativo', 'Mauricio', 'target', 50000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente antiguo', '', 'Clientes antiguos (Recuperación)', '2026-02-28'),
  (2996, 'BBVA', 'BBVA - Transformación cultural', 'Nicolás Aramburú', 'target', 120000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-03-01'),
  (2995, 'Mibanco', 'Mibanco - ¿Cómo ganar en autoconstrucción?', 'Nicolás Aramburú', 'target', 40000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (2994, 'Tebca', 'Tebca - Cultura', 'Nicolás Aramburú', 'target', 30000, 75, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Tecnología', 'Contactos personales (Partners)', '2026-02-13'),
  (2992, 'Nissan', 'Nissan - por definir reto', 'Nicolás Aramburú', 'target', 40000, NULL, '', 'activo', '', '', 'Cliente nuevo', 'Automotriz', 'Contactos personales (Partners)', NULL),
  (2990, 'Credicorp Capital', 'Credicorp Capital - TBD', 'Mauricio', 'target', 0, NULL, '', 'activo', '', '', 'Cliente antiguo', 'Banca', 'Contactos personales (Partners)', NULL),
  (2985, 'Explomin', 'Explomin - planeamiento estratégico', 'Guillermo Solano', 'target', 40000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Canales Mamberos', NULL),
  (2984, 'San Fernando', 'San Fernando - Coaching individual líderes', 'Mauricio', 'cierre', 7600, 75, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Agroindustrial', 'Clientes actuales (Profundización)', '2026-07-01'),
  (2980, 'Banco Falabella Colombia', 'Banco Falabella Colombia - Cultura y estrategia comercial', 'Mauricio', 'cierre', 40000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Banca', 'Contactos personales (Partners)', '2026-07-01'),
  (2979, 'Claro', 'Claro - Planeamiento Cultural', 'Mauricio', 'target', 71000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-03-02'),
  (2978, 'TGP', 'TGP', 'Guillermo Solano', 'target', 30000, NULL, '', 'activo', '', 'Estrategia', 'Cliente actual', '', 'Clientes actuales (Profundización)', NULL),
  (2975, 'Caja Cencosud Scotiabank', 'Caja Cencosud Scotiabank - Experiencia de clientes', 'Nicolás Aramburú', 'cierre', 91000, 25, '', 'activo', '', 'Marca & Experiencia', 'Cliente nuevo', 'Banca', 'Contactos personales (Partners)', '2026-07-31'),
  (2974, 'Reyna Grupo Inmobiliario', 'Reyna Grupo Inmobiliario', 'Guillermo Solano', 'target', 33500, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2025-12-01'),
  (2972, 'San Fernando', 'San Fernando - Planeamiento cultural (empresa)', 'Mauricio', 'target', 40000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', 'Agroindustrial', 'Clientes actuales (Profundización)', '2026-02-28'),
  (2971, 'Orica', 'Orica', 'Mauricio', 'target', 0, NULL, '', 'activo', '', '', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (2970, 'Cruz del Sur', 'Cruz del Sur', 'Mauricio', 'target', 0, NULL, '', 'activo', '', '', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (2966, 'Mercadolibre', 'Mercadolibre - Transformación cultural', 'Nicolás Aramburú', 'target', 50000, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (2963, 'Agrocalera', 'Agrocalera - Plan estratégico', 'Guillermo Solano', 'target', 32000, 25, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (2962, 'DP World', 'DP World - Planeamiento cultural', 'Mauricio', 'target', 55000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-03-02'),
  (2961, 'Equans', 'Equans - Talleres planeamiento estratégico', 'Guillermo Solano', 'nurturing', 7500, 50, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Servicios', 'Contactos personales (Partners)', '2025-12-15'),
  (2960, 'Papel Higiénico Paracas', 'Papel Higiénico Paracas', 'Guillermo Solano', 'nurturing', 10000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (2951, 'Volcan', 'Volcan', 'Guillermo Solano', 'target', 15000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-01-01'),
  (2947, 'Farmacia Universal', 'Farmacia Universal - Transformación liderazgo', 'Mauricio', 'target', 20000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Servicios', 'Canales Mamberos', '2025-12-31'),
  (2942, 'UNACEM', 'UNACEM - Liderazgo Gestión del cambio', 'Mauricio', 'target', 48000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Mamberos', '2025-11-30'),
  (2941, 'Tresa', 'Tresa - Estrategia comercial', 'Nicolás Aramburú', 'target', 52000, 50, '', 'activo', '', '', '', '', 'Canales Mamberos', '2026-01-01'),
  (2940, 'Alpayana', 'Alpayana - Talleres culturales (7) - Yauricocha, Lima y Bolívar', 'Mauricio', 'target', 12500, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', '', 'Clientes actuales (Profundización)', '2025-11-01'),
  (2936, 'Lockton', 'Lockton', 'Guillermo Solano', 'target', 12000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Alianzas comerciales', '2026-01-01'),
  (2932, 'Banco Falabella', 'Falabella Retail - EVP y Marca Empleadora', 'Mauricio', 'target', 26250, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente antiguo', '', 'Contactos personales (Partners)', '2025-12-01'),
  (2929, 'Grupo DC', 'Grupo DC - Patronato Grupo DC', 'Cristina Mc', 'cierre', 140000, 25, '', 'activo', '', 'Marca & Experiencia', 'Cliente actual', 'Servicios', 'Clientes actuales (Profundización)', '2026-06-30'),
  (2924, 'Contact Americas', 'Contact Americas - Liderazgo tribal y cultura', 'Nicolás Aramburú', 'target', 38000, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', 'Servicios', 'Contactos personales (Partners)', '2025-12-01'),
  (2917, 'UNACEM', 'UNACEM - Gestión del cambio', 'Mauricio', 'target', 33000, 25, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Mamberos', '2026-06-03'),
  (2913, 'TGP', 'Negocio TGP', 'Guillermo Solano', 'nurturing', 18000, NULL, '', 'activo', '', 'Estrategia', '', '', 'Contactos personales (Partners)', '2025-11-15'),
  (2911, 'Integratel (telefónica)', 'Integratel - Transformación Cultural', 'Mauricio', 'target', 53000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente antiguo', '', 'Canales Mamberos', '2025-12-02'),
  (2891, 'Universidad César Vallejo', 'Universidad César Vallejo - Estrategia de ventas y propuesta de valor', 'Nicolás Aramburú', 'target', 88000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Educación', 'Senseis', '2025-11-01'),
  (2890, 'Aruma', 'Aruma - Transformación cultural tiendas', 'Nicolás Aramburú', 'target', 101000, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', '', 'Retail', 'Contactos personales (Partners)', '2026-03-01'),
  (2888, 'AVLA', 'AVLA - Offsite estrategia comercial', 'Mauricio', 'target', 0, 50, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2025-11-15'),
  (2877, 'Brother', 'Negocio Brother', 'Guillermo Solano', 'nurturing', 1500, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2025-10-15'),
  (2864, 'Dinet', 'Negocio Dinet', 'Guillermo Solano', 'target', 10000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2025-11-15'),
  (2857, 'BMI', 'BMI - EVP', 'Mauricio', 'target', 0, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', '', 'Clientes actuales (Profundización)', NULL),
  (2856, 'Centenario', 'Centenario - Experiencia del cliente', 'Mauricio', 'target', 0, 50, '', 'activo', '', 'Marca & Experiencia', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL),
  (2854, 'Tramarsa', 'Tramarsa - Cultura de seguridad estibadores', 'Mauricio', 'target', 69000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2025-12-01'),
  (2851, 'Panorama', 'Panorama - Programa Mentor Coach Lucio', 'Mauricio', 'cierre', 3800, 75, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', 'Retail', 'Clientes actuales (Profundización)', '2026-07-30'),
  (2849, 'BMI', 'BMI - Experiencia del cliente y del agente (PDV)', 'Mauricio', 'target', 0, 50, '', 'activo', '', 'Marca & Experiencia', 'Cliente actual', '', 'Clientes actuales (Profundización)', '2025-10-31'),
  (2839, 'Banco Falabella', 'Banco Falabella - Planeamiento cultural', 'Mauricio', 'target', 25000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Clientes antiguos (Recuperación)', '2025-08-31'),
  (2834, 'Statkraft', 'Statkraft - Programa desarrollo de liderazgo', 'Mauricio', 'target', 30000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2025-12-01'),
  (2831, 'Universidad de Piura (UDEP)', 'Universidad de Piura (UDEP) - Estrategia ventas', 'Nicolás Aramburú', 'target', 20000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Educación', 'Mamberos', '2025-11-01'),
  (2829, 'Textil del Valle', 'Textil del Valle - Medición de felicidad', 'Mauricio', 'target', 2500, 31, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente antiguo', '', 'Clientes antiguos (Recuperación)', '2026-01-01'),
  (2825, 'Pacifico Seguros', 'Pacífico Seguros - Gestión del cambio', 'Mauricio', 'target', 0, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Clientes antiguos (Recuperación)', NULL),
  (2816, 'Grupo San Antonio', 'Grupo San Antonio - Bienestar y felicidad', 'Mauricio', 'target', 2500, 90, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2026-01-01'),
  (2803, 'Zicsa', 'Zicsa - Diagnóstico estratégico cultural', 'Mauricio', 'nurturing', 16000, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', '2025-07-31'),
  (2798, 'Maquinarias', 'Maquinarias - Estrategia comercial', 'Nicolás Aramburú', 'target', 30000, NULL, '', 'activo', '', 'Estrategia', 'Cliente nuevo', 'Automotriz', 'Senseis', '2025-12-01'),
  (2793, 'Prima AFP Seguros', 'Prima AFP - Gestión del cambio', 'Mauricio', 'target', 0, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente antiguo', '', 'Clientes antiguos (Recuperación)', NULL),
  (2792, 'Prima AFP', 'Prima AFP - Medición Cultura de Felicidad', 'Mauricio', 'target', 2500, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', '', '', 'Clientes antiguos (Recuperación)', '2026-01-01'),
  (2785, 'Grupo Pana', 'Grupo Pana - Plan cultural', 'Mauricio', 'target', 14000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Canales Mamberos', '2026-01-01'),
  (2684, 'Pacífico', 'Asesorías directivas Cultura Prima AFP', 'Mauricio', 'target', 6000, 40, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', '', 'Clientes actuales (Profundización)', '2025-05-01'),
  (2683, 'Prima AFP', 'Indice Cultural Credicorp', 'Mauricio', 'target', 10000, 50, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente actual', '', 'Clientes actuales (Profundización)', '2025-06-01'),
  (2595, 'Servifreno', 'Servifreno - Continuación', 'Guillermo Solano', 'nurturing', 12000, 50, '', 'activo', '', 'Estrategia', 'Cliente antiguo', '', 'Clientes actuales (Profundización)', '2025-06-01'),
  (2453, 'Prima AFP', 'Marca Empleadora Prima AFP', 'Mauricio', 'target', 22500, 25, '', 'activo', '', 'Marca & Experiencia', 'Cliente nuevo', '', 'Clientes actuales (Profundización)', '2024-11-01'),
  (2320, 'OMG', 'Planeamiento cultural', 'Mauricio', 'target', 0, NULL, '', 'activo', '', 'Cultura, Talento & Liderazgo', 'Cliente nuevo', '', 'Contactos personales (Partners)', NULL)
;
