// mambo - Pipeline piloto Peru. SEED_DEALS generado desde el CSV real (131 negocios).
// NO editar a mano: regenerar desde el CSV. index.html carga este archivo al iniciar.

const SEED_DEALS =
[
    {
        "id":  1,
        "org":  "Banco Santander",
        "title":  "Banco Santander - gestión del cambio",
        "owner":  "Nicolás Aramburú",
        "stage":  "primera",
        "amount":  80000,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Senseis",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  2,
        "org":  "Equans",
        "title":  "Equans - Coaching individual al liderazgo",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  3500,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-08-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  3,
        "org":  "Equans",
        "title":  "Equans - Cadena de valor de talento (reclutamiento y onboarding)",
        "owner":  "Mauricio",
        "stage":  "primera",
        "amount":  20000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-09-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  4,
        "org":  "La Calera",
        "title":  "La Calera - Talleres cultura y clima",
        "owner":  "Cristina Mc",
        "stage":  "propuesta",
        "amount":  3000,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  5,
        "org":  "Terminales Portuarios Euroandinos",
        "title":  "Terminales Portuarios Euroandinos",
        "owner":  "Guillermo Solano",
        "stage":  "contacto",
        "amount":  20000,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-28",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  6,
        "org":  "OSTERLING ABOGADOS",
        "title":  "OSTERLING ABOGADOS",
        "owner":  "Renzo Duarte",
        "stage":  "contacto",
        "amount":  0,
        "prob":  25,
        "vertical":  "",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Mamberos",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  7,
        "org":  "PC MODA SAC",
        "title":  "PC MODA SAC",
        "owner":  "Renzo Duarte",
        "stage":  "contacto",
        "amount":  0,
        "prob":  25,
        "vertical":  "",
        "clientType":  "Cliente nuevo",
        "industry":  "Textil",
        "source":  "Mamberos",
        "closeDate":  "2026-07-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  8,
        "org":  "UNACEM",
        "title":  "UNACEM - plan de tecnología para gestión humana",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  18000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "Industrial",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  9,
        "org":  "Montana",
        "title":  "Montana - Planeamiento + Transformación Digital",
        "owner":  "Renzo Duarte",
        "stage":  "propuesta",
        "amount":  25000,
        "prob":  75,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  10,
        "org":  "Montana",
        "title":  "Montana - AI",
        "owner":  "Renzo Duarte",
        "stage":  "primera",
        "amount":  15000,
        "prob":  50,
        "vertical":  "Transformación Digital",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-08-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  11,
        "org":  "FAO",
        "title":  "FAO",
        "owner":  "Renzo Duarte",
        "stage":  "contacto",
        "amount":  0,
        "prob":  25,
        "vertical":  "Transformación Digital",
        "clientType":  "Cliente nuevo",
        "industry":  "Agroindustrial",
        "source":  "Mamberos",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  12,
        "org":  "Credicorp Capital",
        "title":  "Credicorp Capital - transformación cultural",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  71000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Banca",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  13,
        "org":  "Abbott",
        "title":  "Abbott - transformación cultural",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  18000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Salud",
        "source":  "Senseis",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  14,
        "org":  "Bituper",
        "title":  "Bituper - Estrategia Comercial",
        "owner":  "Guillermo Solano",
        "stage":  "cierre",
        "amount":  17000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "Infraestructura, servicios y construcción",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-18",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  15,
        "org":  "Falabella",
        "title":  "Falabella - modelo de liderazgo",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  36000,
        "prob":  75,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Retail",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-19",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  16,
        "org":  "Interbank",
        "title":  "Interbank - Gestión del Cambio",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  100000,
        "prob":  75,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Banca",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-06-19",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  17,
        "org":  "Indeco - Lanzark",
        "title":  "Indeco",
        "owner":  "Renzo Duarte",
        "stage":  "primera",
        "amount":  15000,
        "prob":  50,
        "vertical":  "Transformación Digital",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  18,
        "org":  "Equans",
        "title":  "Equans - Programa de Mentoring",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  13500,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "Servicios",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  19,
        "org":  "JyS Asesoria Empresarial",
        "title":  "JyS Asesoria Empresarial - Planeamiento Estrategico",
        "owner":  "Cristina Mc",
        "stage":  "cierre",
        "amount":  24000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-06-22",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  20,
        "org":  "JyS Asesoria Empresarial",
        "title":  "JyS Asesoria Empresarial - Branding",
        "owner":  "Cristina Mc",
        "stage":  "cierre",
        "amount":  8000,
        "prob":  25,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  21,
        "org":  "Bancomercio",
        "title":  "Bancomercio",
        "owner":  "Renzo Duarte",
        "stage":  "cierre",
        "amount":  20000,
        "prob":  75,
        "vertical":  "Transformación Digital",
        "clientType":  "Cliente antiguo",
        "industry":  "Banca",
        "source":  "Mamberos",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  22,
        "org":  "UNACEM",
        "title":  "UNACEM- Comunicacion Interna",
        "owner":  "Cristina Mc",
        "stage":  "nurturing",
        "amount":  25000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "Industrial",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-06-03",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  23,
        "org":  "Gallagher",
        "title":  "Gallagher",
        "owner":  "Renzo Duarte",
        "stage":  "contacto",
        "amount":  0,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Mamberos",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  24,
        "org":  "Fibra Prime",
        "title":  "Fibra Prime - Digitalización",
        "owner":  "Cristina Mc",
        "stage":  "contacto",
        "amount":  0,
        "prob":  null,
        "vertical":  "Transformación Digital",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  25,
        "org":  "Olympic",
        "title":  "Olympic - Estrategia de reposicionamiento Gas",
        "owner":  "Cristina Mc",
        "stage":  "cierre",
        "amount":  35000,
        "prob":  50,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "Cliente nuevo",
        "industry":  "Petróleo y gas",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-18",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  26,
        "org":  "Ecopacking",
        "title":  "Ecopacking - Campaña de posicionamiento",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  10000,
        "prob":  50,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "Cliente actual",
        "industry":  "Industrial",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-08",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  27,
        "org":  "Yichang",
        "title":  "Yichang - AI discovery",
        "owner":  "Nicolás Aramburú",
        "stage":  "contacto",
        "amount":  20000,
        "prob":  null,
        "vertical":  "Transformación Digital",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  28,
        "org":  "Agrícola Don Ricardo",
        "title":  "Agrícola Don Ricardo - Planeamiento estratégico",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  42000,
        "prob":  25,
        "vertical":  "Estrategia",
        "clientType":  "Cliente actual",
        "industry":  "Agroindustrial",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-09-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  29,
        "org":  "La Dominga",
        "title":  "La Dominga - Propuesta de valor y experiencia del cliente",
        "owner":  "Cristina Mc",
        "stage":  "contacto",
        "amount":  0,
        "prob":  null,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  30,
        "org":  "REF",
        "title":  "REF - Coaching líderes (Chene)",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  3500,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-08-06",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  31,
        "org":  "Inkas Berries",
        "title":  "Inkas Berries - por verse",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  0,
        "prob":  null,
        "vertical":  "",
        "clientType":  "",
        "industry":  "",
        "source":  "",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  32,
        "org":  "Belmond",
        "title":  "Belmond - EVP",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  20000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Hotelería y Turismo",
        "source":  "Senseis",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  33,
        "org":  "Grupo Kaufmann",
        "title":  "Grupo Kaufmann",
        "owner":  "Renzo Duarte",
        "stage":  "contacto",
        "amount":  20000,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  34,
        "org":  "Grupo Andino",
        "title":  "Grupo Andino - planeamiento estratégico cultural",
        "owner":  "Renzo Duarte",
        "stage":  "primera",
        "amount":  20000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-08-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  35,
        "org":  "Cementos Pacasmayo",
        "title":  "Cementos Pacasmayo",
        "owner":  "Renzo Duarte",
        "stage":  "primera",
        "amount":  20000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  36,
        "org":  "Renzo Costa",
        "title":  "Renzo Costa - Programa de liderazgo",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  10000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  37,
        "org":  "CSTI Corp",
        "title":  "CSTI Corp - Capacitacion IA",
        "owner":  "Cristina Mc",
        "stage":  "target",
        "amount":  0,
        "prob":  null,
        "vertical":  "",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  38,
        "org":  "Fonafe",
        "title":  "Fonafe",
        "owner":  "Guillermo Solano",
        "stage":  "cierre",
        "amount":  45000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-07-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  39,
        "org":  "Pisco Lablanco",
        "title":  "Energy Drinks - Investigación de Mercado",
        "owner":  "Guillermo Solano",
        "stage":  "cierre",
        "amount":  38000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "Bebidas",
        "source":  "Mamberos",
        "closeDate":  "2026-07-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  40,
        "org":  "Farmacia Universal",
        "title":  "Farmacia Universal - Proyecto 2",
        "owner":  "Mauricio",
        "stage":  "contacto",
        "amount":  15000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-07-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  41,
        "org":  "Farmacia Universal",
        "title":  "Farmacia Universal - Planeamiento estratégico",
        "owner":  "Mauricio",
        "stage":  "contacto",
        "amount":  20000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  42,
        "org":  "VyV Inmobiliaria",
        "title":  "VyV Inmobiliaria - Capacitación liderazgo y cultura",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  10000,
        "prob":  75,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Infraestructura, servicios y construcción",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  43,
        "org":  "Pacific Control (Laboratorios Scerpella)",
        "title":  "Pacific Control - Cultura",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  40125,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Mamberos",
        "closeDate":  "2026-07-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  44,
        "org":  "San Fernando",
        "title":  "San Fernando - Procesos",
        "owner":  "Mauricio",
        "stage":  "primera",
        "amount":  15000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Clientes antiguos (Recuperación)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  45,
        "org":  "Aceros Arequipa",
        "title":  "Aceros Arequipa - Planeamiento Cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  40000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Industrial",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  46,
        "org":  "Celaris",
        "title":  "Celaris - Gestión de RS",
        "owner":  "Topless",
        "stage":  "target",
        "amount":  0,
        "prob":  25,
        "vertical":  "",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Senseis",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  47,
        "org":  "Montana",
        "title":  "Implementación TI Proyectos",
        "owner":  "Renzo Duarte",
        "stage":  "primera",
        "amount":  50000,
        "prob":  50,
        "vertical":  "Transformación Digital",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-04-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  48,
        "org":  "Redondos",
        "title":  "Redondos - Cultura de Felicidad",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  10000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Senseis",
        "closeDate":  "2026-05-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  49,
        "org":  "VyV Inmobiliaria",
        "title":  "VyV Inmobiliaria - Cultura y liderazgo",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  40000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Infraestructura, servicios y construcción",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  50,
        "org":  "Alliance Risk \u0026 Protection",
        "title":  "Alliance Risk \u0026 Protection - Diagnostico Cultural",
        "owner":  "Topless",
        "stage":  "target",
        "amount":  0,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  51,
        "org":  "Ficohsa",
        "title":  "Ficohsa",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  61000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Banca",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  52,
        "org":  "Banbif",
        "title":  "Banbif - EVP y marca empleadora",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  30000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Banca",
        "source":  "Mamberos",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  53,
        "org":  "Inka Tubos",
        "title":  "Inka Tubos",
        "owner":  "Guillermo Solano",
        "stage":  "target",
        "amount":  30000,
        "prob":  25,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Senseis",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  54,
        "org":  "Peru Fashions",
        "title":  "Peru Fashions",
        "owner":  "Renzo Duarte",
        "stage":  "contacto",
        "amount":  20000,
        "prob":  25,
        "vertical":  "Estrategia",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-05-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  55,
        "org":  "Blu",
        "title":  "Blu",
        "owner":  "Renzo Duarte",
        "stage":  "primera",
        "amount":  40000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-05-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  56,
        "org":  "Terpel",
        "title":  "Terpel - Capacitaciones mandos medios y analistas (Belen)",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  20000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Mamberos",
        "closeDate":  "2026-06-11",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  57,
        "org":  "Terpel",
        "title":  "Terpel - Planeamiento cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  42500,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Mamberos",
        "closeDate":  "2026-06-11",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  58,
        "org":  "MEF",
        "title":  "MEF - Planeamiento cultural",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  53500,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-08-03",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  59,
        "org":  "UNACEM",
        "title":  "UNACEM",
        "owner":  "Guillermo Solano",
        "stage":  "nurturing",
        "amount":  72000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente actual",
        "industry":  "Industrial",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  60,
        "org":  "Montana",
        "title":  "Sostenibilidad",
        "owner":  "Renzo Duarte",
        "stage":  "target",
        "amount":  20000,
        "prob":  50,
        "vertical":  "Ventas",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Mamberos",
        "closeDate":  "2026-03-28",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  61,
        "org":  "MEF",
        "title":  "MEF - índice y esencia cultural",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  11000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-08-13",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  62,
        "org":  "Tailoy",
        "title":  "Tailoy",
        "owner":  "Renzo Duarte",
        "stage":  "primera",
        "amount":  30000,
        "prob":  25,
        "vertical":  "Ventas",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-03-28",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  63,
        "org":  "DC Capital",
        "title":  "Grupo DC- Manual de Crisis Empresas",
        "owner":  "Cristina Mc",
        "stage":  "nurturing",
        "amount":  20000,
        "prob":  25,
        "vertical":  "",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  64,
        "org":  "Grupo Minero Sinchi Wayra",
        "title":  "Grupo Minero Sinchi Wayra - transformación cultural desde el liderazgo",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  40000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Minería",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-06",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  65,
        "org":  "Terpel",
        "title":  "Terpel- Marca Vehículo Cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  33000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-06-11",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  66,
        "org":  "Oeschle",
        "title":  "Oeschle - Planeamiento cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  30000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Retail",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  67,
        "org":  "Catalogo SAC",
        "title":  "Catalogo SAC",
        "owner":  "Renzo Duarte",
        "stage":  "target",
        "amount":  98000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Textil",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-03-19",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  68,
        "org":  "Caja Cusco",
        "title":  "Caja Cusco",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  30000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-02-27",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  69,
        "org":  "Zest Capital",
        "title":  "Zest Capital",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  10000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-02-28",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  70,
        "org":  "Illusione",
        "title":  "Illusione - Automatización de procesos de clientes",
        "owner":  "Renzo Duarte",
        "stage":  "target",
        "amount":  30000,
        "prob":  75,
        "vertical":  "Transformación Digital",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-15",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  71,
        "org":  "Yape (iO)",
        "title":  "Yape (iO)",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  10000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-03-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  72,
        "org":  "BBB",
        "title":  "BBB - transformación cultural y ventas",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  30000,
        "prob":  75,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Retail",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-02-23",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  73,
        "org":  "Banco Pichincha",
        "title":  "Banco Pichincha - Operativización del nuevo modelo operativo",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  50000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Clientes antiguos (Recuperación)",
        "closeDate":  "2026-02-28",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  74,
        "org":  "BBVA",
        "title":  "BBVA - Transformación cultural",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  120000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-03-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  75,
        "org":  "Mibanco",
        "title":  "Mibanco - ¿Cómo ganar en autoconstrucción?",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  40000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  76,
        "org":  "Tebca",
        "title":  "Tebca - Cultura",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  30000,
        "prob":  75,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Tecnología",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-02-13",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  77,
        "org":  "Nissan",
        "title":  "Nissan - por definir reto",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  40000,
        "prob":  null,
        "vertical":  "",
        "clientType":  "Cliente nuevo",
        "industry":  "Automotriz",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  78,
        "org":  "Credicorp Capital",
        "title":  "Credicorp Capital - TBD",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  null,
        "vertical":  "",
        "clientType":  "Cliente antiguo",
        "industry":  "Banca",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  79,
        "org":  "Explomin",
        "title":  "Explomin - planeamiento estratégico",
        "owner":  "Guillermo Solano",
        "stage":  "target",
        "amount":  40000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  80,
        "org":  "San Fernando",
        "title":  "San Fernando - Coaching individual líderes",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  7600,
        "prob":  75,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Agroindustrial",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-06-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  81,
        "org":  "Banco Falabella Colombia",
        "title":  "Banco Falabella Colombia - Cultura y estrategia comercial",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  40000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Banca",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  82,
        "org":  "Claro",
        "title":  "Claro - Planeamiento Cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  71000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-03-02",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  83,
        "org":  "TGP",
        "title":  "TGP",
        "owner":  "Guillermo Solano",
        "stage":  "target",
        "amount":  30000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  84,
        "org":  "Caja Cencosud Scotiabank",
        "title":  "Caja Cencosud Scotiabank - Experiencia de clientes",
        "owner":  "Nicolás Aramburú",
        "stage":  "cierre",
        "amount":  91000,
        "prob":  25,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "Cliente nuevo",
        "industry":  "Banca",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-07-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  85,
        "org":  "Reyna Grupo Inmobiliario",
        "title":  "Reyna Grupo Inmobiliario",
        "owner":  "Guillermo Solano",
        "stage":  "target",
        "amount":  33500,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-12-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  86,
        "org":  "San Fernando",
        "title":  "San Fernando - Planeamiento cultural (empresa)",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  40000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-02-28",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  87,
        "org":  "Orica",
        "title":  "Orica",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  null,
        "vertical":  "",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  88,
        "org":  "Cruz del Sur",
        "title":  "Cruz del Sur",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  null,
        "vertical":  "",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  89,
        "org":  "Mercadolibre",
        "title":  "Mercadolibre - Transformación cultural",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  50000,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  90,
        "org":  "Agrocalera",
        "title":  "Agrocalera - Plan estratégico",
        "owner":  "Guillermo Solano",
        "stage":  "target",
        "amount":  32000,
        "prob":  25,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  91,
        "org":  "DP World",
        "title":  "DP World - Planeamiento cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  55000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-03-02",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  92,
        "org":  "Equans",
        "title":  "Equans - Talleres planeamiento estratégico",
        "owner":  "Guillermo Solano",
        "stage":  "nurturing",
        "amount":  7500,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-12-15",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  93,
        "org":  "Papel Higiénico Paracas",
        "title":  "Papel Higiénico Paracas",
        "owner":  "Guillermo Solano",
        "stage":  "nurturing",
        "amount":  10000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  94,
        "org":  "Volcan",
        "title":  "Volcan",
        "owner":  "Guillermo Solano",
        "stage":  "target",
        "amount":  15000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-01-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  95,
        "org":  "Farmacia Universal",
        "title":  "Farmacia Universal - Transformación liderazgo",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  20000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "2025-12-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  96,
        "org":  "UNACEM",
        "title":  "UNACEM - Liderazgo Gestión del cambio",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  48000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Mamberos",
        "closeDate":  "2025-11-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  97,
        "org":  "Tresa",
        "title":  "Tresa - Estrategia comercial",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  52000,
        "prob":  50,
        "vertical":  "",
        "clientType":  "",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-01-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  98,
        "org":  "Alpayana",
        "title":  "Alpayana - Talleres culturales (7) - Yauricocha, Lima y Bolívar",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  12500,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2025-11-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  99,
        "org":  "Lockton",
        "title":  "Lockton",
        "owner":  "Guillermo Solano",
        "stage":  "target",
        "amount":  12000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Alianzas comerciales",
        "closeDate":  "2026-01-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  100,
        "org":  "Banco Falabella",
        "title":  "Falabella Retail - EVP y Marca Empleadora",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  26250,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-12-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  101,
        "org":  "Grupo DC",
        "title":  "Grupo DC - Patronato Grupo DC",
        "owner":  "Cristina Mc",
        "stage":  "cierre",
        "amount":  140000,
        "prob":  25,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "Cliente actual",
        "industry":  "Servicios",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-05-29",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  102,
        "org":  "Contact Americas",
        "title":  "Contact Americas - Liderazgo tribal y cultura",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  38000,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "Servicios",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-12-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  103,
        "org":  "UNACEM",
        "title":  "UNACEM - Gestión del cambio",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  33000,
        "prob":  25,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Mamberos",
        "closeDate":  "2026-06-03",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  104,
        "org":  "TGP",
        "title":  "Negocio TGP",
        "owner":  "Guillermo Solano",
        "stage":  "nurturing",
        "amount":  18000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-11-15",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  105,
        "org":  "Integratel (telefónica)",
        "title":  "Integratel - Transformación Cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  53000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "2025-12-02",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  106,
        "org":  "Universidad César Vallejo",
        "title":  "Universidad César Vallejo - Estrategia de ventas y propuesta de valor",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  88000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "Educación",
        "source":  "Senseis",
        "closeDate":  "2025-11-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  107,
        "org":  "Aruma",
        "title":  "Aruma - Transformación cultural tiendas",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  101000,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "",
        "industry":  "Retail",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-03-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  108,
        "org":  "AVLA",
        "title":  "AVLA - Offsite estrategia comercial",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-11-15",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  109,
        "org":  "Brother",
        "title":  "Negocio Brother",
        "owner":  "Guillermo Solano",
        "stage":  "nurturing",
        "amount":  1500,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-10-15",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  110,
        "org":  "Dinet",
        "title":  "Negocio Dinet",
        "owner":  "Guillermo Solano",
        "stage":  "target",
        "amount":  10000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-11-15",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  111,
        "org":  "BMI",
        "title":  "BMI - EVP",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  112,
        "org":  "Centenario",
        "title":  "Centenario - Experiencia del cliente",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  50,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  113,
        "org":  "Tramarsa",
        "title":  "Tramarsa - Cultura de seguridad estibadores",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  69000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-12-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  114,
        "org":  "Panorama",
        "title":  "Panorama - Programa Mentor Coach Lucio",
        "owner":  "Mauricio",
        "stage":  "cierre",
        "amount":  3800,
        "prob":  75,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "Retail",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2026-07-30",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  115,
        "org":  "BMI",
        "title":  "BMI - Experiencia del cliente y del agente (PDV)",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  50,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2025-10-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  116,
        "org":  "Banco Falabella",
        "title":  "Banco Falabella - Planeamiento cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  25000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Clientes antiguos (Recuperación)",
        "closeDate":  "2025-08-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  117,
        "org":  "Statkraft",
        "title":  "Statkraft - Programa desarrollo de liderazgo",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  30000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-12-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  118,
        "org":  "Universidad de Piura (UDEP)",
        "title":  "Universidad de Piura (UDEP) - Estrategia ventas",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  20000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "Educación",
        "source":  "Mamberos",
        "closeDate":  "2025-11-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  119,
        "org":  "Textil del Valle",
        "title":  "Textil del Valle - Medición de felicidad",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  2500,
        "prob":  31,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Clientes antiguos (Recuperación)",
        "closeDate":  "2026-01-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  120,
        "org":  "Pacifico Seguros",
        "title":  "Pacífico Seguros - Gestión del cambio",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Clientes antiguos (Recuperación)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  121,
        "org":  "Grupo San Antonio",
        "title":  "Grupo San Antonio - Bienestar y felicidad",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  2500,
        "prob":  90,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2026-01-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  122,
        "org":  "Zicsa",
        "title":  "Zicsa - Diagnóstico estratégico cultural",
        "owner":  "Mauricio",
        "stage":  "nurturing",
        "amount":  16000,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "2025-07-31",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  123,
        "org":  "Maquinarias",
        "title":  "Maquinarias - Estrategia comercial",
        "owner":  "Nicolás Aramburú",
        "stage":  "target",
        "amount":  30000,
        "prob":  null,
        "vertical":  "Estrategia",
        "clientType":  "Cliente nuevo",
        "industry":  "Automotriz",
        "source":  "Senseis",
        "closeDate":  "2025-12-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  124,
        "org":  "Prima AFP Seguros",
        "title":  "Prima AFP - Gestión del cambio",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Clientes antiguos (Recuperación)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  125,
        "org":  "Prima AFP",
        "title":  "Prima AFP - Medición Cultura de Felicidad",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  2500,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "",
        "industry":  "",
        "source":  "Clientes antiguos (Recuperación)",
        "closeDate":  "2026-01-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  126,
        "org":  "Grupo Pana",
        "title":  "Grupo Pana - Plan cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  14000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Canales Mamberos",
        "closeDate":  "2026-01-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  127,
        "org":  "Pacífico",
        "title":  "Asesorías directivas Cultura Prima AFP",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  6000,
        "prob":  40,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2025-05-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  128,
        "org":  "Prima AFP",
        "title":  "Indice Cultural Credicorp",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  10000,
        "prob":  50,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente actual",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2025-06-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  129,
        "org":  "Servifreno",
        "title":  "Servifreno - Continuación",
        "owner":  "Guillermo Solano",
        "stage":  "nurturing",
        "amount":  12000,
        "prob":  50,
        "vertical":  "Estrategia",
        "clientType":  "Cliente antiguo",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2025-06-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  130,
        "org":  "Prima AFP",
        "title":  "Marca Empleadora Prima AFP",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  22500,
        "prob":  25,
        "vertical":  "Marca \u0026 Experiencia",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Clientes actuales (Profundización)",
        "closeDate":  "2024-11-01",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    },
    {
        "id":  131,
        "org":  "OMG",
        "title":  "Planeamiento cultural",
        "owner":  "Mauricio",
        "stage":  "target",
        "amount":  0,
        "prob":  null,
        "vertical":  "Cultura, Talento \u0026 Liderazgo",
        "clientType":  "Cliente nuevo",
        "industry":  "",
        "source":  "Contactos personales (Partners)",
        "closeDate":  "",
        "comment":  "",
        "status":  "activo",
        "lossReason":  ""
    }
]
;

// Catalogos del modelo
const STAGES = [
  { id: "target",    label: "Target",                    bg: "#B7DBF1", text: "#003179" },
  { id: "primera",   label: "Primera reunión",           bg: "#E7EEFF", text: "#1E56CD" },
  { id: "contacto",  label: "Contacto establecido",      bg: "#1E56CD", text: "#FFFFFF" },
  { id: "propuesta", label: "Presentación de propuesta", bg: "#003179", text: "#FFFFFF" },
  { id: "cierre",    label: "Follow-up y cierre",        bg: "#FA5478", text: "#FFFFFF" },
  { id: "nurturing", label: "Nurturing",                 bg: "#DCD7FF", text: "#1D0446" }
];

const LOSS_REASONS = [
  "Precio / presupuesto",
  "Eligió a un competidor",
  "No es el momento",
  "Sin respuesta / se enfrió",
  "Cambio de prioridades",
  "No calificaba (mal fit)"
];

const SEED_VERSION = "2026-06-22-segunda-base";

// Partners del piloto. La lista del selector "¿Quién eres?" es la unión de estos
// con los propietarios que existan en los datos cargados (por si aparece alguno nuevo).
const OWNERS = [
  "Nicolás Aramburú",
  "Renzo Duarte",
  "Cristina Mc",
  "Guillermo Solano",
  "Mauricio",
  "Topless"
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { SEED_DEALS, STAGES, LOSS_REASONS, SEED_VERSION, OWNERS };
}
